// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MarkerMsg.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _MARKERMSG_H_
#define _MARKERMSG_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MarkerMsg_SOURCE)
#define MarkerMsg_DllAPI __declspec( dllexport )
#else
#define MarkerMsg_DllAPI __declspec( dllimport )
#endif // MarkerMsg_SOURCE
#else
#define MarkerMsg_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MarkerMsg_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure MarkerMsg defined by the user in the IDL file.
 * @ingroup MARKERMSG
 */
class MarkerMsg
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MarkerMsg();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MarkerMsg();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object MarkerMsg that will be copied.
     */
    eProsima_user_DllExport MarkerMsg(
            const MarkerMsg& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object MarkerMsg that will be copied.
     */
    eProsima_user_DllExport MarkerMsg(
            MarkerMsg&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object MarkerMsg that will be copied.
     */
    eProsima_user_DllExport MarkerMsg& operator =(
            const MarkerMsg& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object MarkerMsg that will be copied.
     */
    eProsima_user_DllExport MarkerMsg& operator =(
            MarkerMsg&& x);

    /*!
     * @brief This function sets a value in member seq
     * @param _seq New value for member seq
     */
    eProsima_user_DllExport void seq(
            uint32_t _seq);

    /*!
     * @brief This function returns the value of member seq
     * @return Value of member seq
     */
    eProsima_user_DllExport uint32_t seq() const;

    /*!
     * @brief This function returns a reference to member seq
     * @return Reference to member seq
     */
    eProsima_user_DllExport uint32_t& seq();

    /*!
     * @brief This function sets a value in member secs
     * @param _secs New value for member secs
     */
    eProsima_user_DllExport void secs(
            uint32_t _secs);

    /*!
     * @brief This function returns the value of member secs
     * @return Value of member secs
     */
    eProsima_user_DllExport uint32_t secs() const;

    /*!
     * @brief This function returns a reference to member secs
     * @return Reference to member secs
     */
    eProsima_user_DllExport uint32_t& secs();

    /*!
     * @brief This function sets a value in member nsecs
     * @param _nsecs New value for member nsecs
     */
    eProsima_user_DllExport void nsecs(
            uint32_t _nsecs);

    /*!
     * @brief This function returns the value of member nsecs
     * @return Value of member nsecs
     */
    eProsima_user_DllExport uint32_t nsecs() const;

    /*!
     * @brief This function returns a reference to member nsecs
     * @return Reference to member nsecs
     */
    eProsima_user_DllExport uint32_t& nsecs();

    /*!
     * @brief This function copies the value in member frame_id
     * @param _frame_id New value to be copied in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            const std::string& _frame_id);

    /*!
     * @brief This function moves the value in member frame_id
     * @param _frame_id New value to be moved in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            std::string&& _frame_id);

    /*!
     * @brief This function returns a constant reference to member frame_id
     * @return Constant reference to member frame_id
     */
    eProsima_user_DllExport const std::string& frame_id() const;

    /*!
     * @brief This function returns a reference to member frame_id
     * @return Reference to member frame_id
     */
    eProsima_user_DllExport std::string& frame_id();
    /*!
     * @brief This function copies the value in member ns
     * @param _ns New value to be copied in member ns
     */
    eProsima_user_DllExport void ns(
            const std::string& _ns);

    /*!
     * @brief This function moves the value in member ns
     * @param _ns New value to be moved in member ns
     */
    eProsima_user_DllExport void ns(
            std::string&& _ns);

    /*!
     * @brief This function returns a constant reference to member ns
     * @return Constant reference to member ns
     */
    eProsima_user_DllExport const std::string& ns() const;

    /*!
     * @brief This function returns a reference to member ns
     * @return Reference to member ns
     */
    eProsima_user_DllExport std::string& ns();
    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    eProsima_user_DllExport void id(
            int32_t _id);

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    eProsima_user_DllExport int32_t id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport int32_t& id();

    /*!
     * @brief This function sets a value in member type
     * @param _type New value for member type
     */
    eProsima_user_DllExport void type(
            int32_t _type);

    /*!
     * @brief This function returns the value of member type
     * @return Value of member type
     */
    eProsima_user_DllExport int32_t type() const;

    /*!
     * @brief This function returns a reference to member type
     * @return Reference to member type
     */
    eProsima_user_DllExport int32_t& type();

    /*!
     * @brief This function sets a value in member action
     * @param _action New value for member action
     */
    eProsima_user_DllExport void action(
            int32_t _action);

    /*!
     * @brief This function returns the value of member action
     * @return Value of member action
     */
    eProsima_user_DllExport int32_t action() const;

    /*!
     * @brief This function returns a reference to member action
     * @return Reference to member action
     */
    eProsima_user_DllExport int32_t& action();

    /*!
     * @brief This function sets a value in member position_x
     * @param _position_x New value for member position_x
     */
    eProsima_user_DllExport void position_x(
            float _position_x);

    /*!
     * @brief This function returns the value of member position_x
     * @return Value of member position_x
     */
    eProsima_user_DllExport float position_x() const;

    /*!
     * @brief This function returns a reference to member position_x
     * @return Reference to member position_x
     */
    eProsima_user_DllExport float& position_x();

    /*!
     * @brief This function sets a value in member position_y
     * @param _position_y New value for member position_y
     */
    eProsima_user_DllExport void position_y(
            float _position_y);

    /*!
     * @brief This function returns the value of member position_y
     * @return Value of member position_y
     */
    eProsima_user_DllExport float position_y() const;

    /*!
     * @brief This function returns a reference to member position_y
     * @return Reference to member position_y
     */
    eProsima_user_DllExport float& position_y();

    /*!
     * @brief This function sets a value in member position_z
     * @param _position_z New value for member position_z
     */
    eProsima_user_DllExport void position_z(
            float _position_z);

    /*!
     * @brief This function returns the value of member position_z
     * @return Value of member position_z
     */
    eProsima_user_DllExport float position_z() const;

    /*!
     * @brief This function returns a reference to member position_z
     * @return Reference to member position_z
     */
    eProsima_user_DllExport float& position_z();

    /*!
     * @brief This function sets a value in member orientation_x
     * @param _orientation_x New value for member orientation_x
     */
    eProsima_user_DllExport void orientation_x(
            float _orientation_x);

    /*!
     * @brief This function returns the value of member orientation_x
     * @return Value of member orientation_x
     */
    eProsima_user_DllExport float orientation_x() const;

    /*!
     * @brief This function returns a reference to member orientation_x
     * @return Reference to member orientation_x
     */
    eProsima_user_DllExport float& orientation_x();

    /*!
     * @brief This function sets a value in member orientation_y
     * @param _orientation_y New value for member orientation_y
     */
    eProsima_user_DllExport void orientation_y(
            float _orientation_y);

    /*!
     * @brief This function returns the value of member orientation_y
     * @return Value of member orientation_y
     */
    eProsima_user_DllExport float orientation_y() const;

    /*!
     * @brief This function returns a reference to member orientation_y
     * @return Reference to member orientation_y
     */
    eProsima_user_DllExport float& orientation_y();

    /*!
     * @brief This function sets a value in member orientation_z
     * @param _orientation_z New value for member orientation_z
     */
    eProsima_user_DllExport void orientation_z(
            float _orientation_z);

    /*!
     * @brief This function returns the value of member orientation_z
     * @return Value of member orientation_z
     */
    eProsima_user_DllExport float orientation_z() const;

    /*!
     * @brief This function returns a reference to member orientation_z
     * @return Reference to member orientation_z
     */
    eProsima_user_DllExport float& orientation_z();

    /*!
     * @brief This function sets a value in member orientation_w
     * @param _orientation_w New value for member orientation_w
     */
    eProsima_user_DllExport void orientation_w(
            float _orientation_w);

    /*!
     * @brief This function returns the value of member orientation_w
     * @return Value of member orientation_w
     */
    eProsima_user_DllExport float orientation_w() const;

    /*!
     * @brief This function returns a reference to member orientation_w
     * @return Reference to member orientation_w
     */
    eProsima_user_DllExport float& orientation_w();

    /*!
     * @brief This function sets a value in member scale_x
     * @param _scale_x New value for member scale_x
     */
    eProsima_user_DllExport void scale_x(
            float _scale_x);

    /*!
     * @brief This function returns the value of member scale_x
     * @return Value of member scale_x
     */
    eProsima_user_DllExport float scale_x() const;

    /*!
     * @brief This function returns a reference to member scale_x
     * @return Reference to member scale_x
     */
    eProsima_user_DllExport float& scale_x();

    /*!
     * @brief This function sets a value in member scale_y
     * @param _scale_y New value for member scale_y
     */
    eProsima_user_DllExport void scale_y(
            float _scale_y);

    /*!
     * @brief This function returns the value of member scale_y
     * @return Value of member scale_y
     */
    eProsima_user_DllExport float scale_y() const;

    /*!
     * @brief This function returns a reference to member scale_y
     * @return Reference to member scale_y
     */
    eProsima_user_DllExport float& scale_y();

    /*!
     * @brief This function sets a value in member scale_z
     * @param _scale_z New value for member scale_z
     */
    eProsima_user_DllExport void scale_z(
            float _scale_z);

    /*!
     * @brief This function returns the value of member scale_z
     * @return Value of member scale_z
     */
    eProsima_user_DllExport float scale_z() const;

    /*!
     * @brief This function returns a reference to member scale_z
     * @return Reference to member scale_z
     */
    eProsima_user_DllExport float& scale_z();

    /*!
     * @brief This function sets a value in member color_r
     * @param _color_r New value for member color_r
     */
    eProsima_user_DllExport void color_r(
            float _color_r);

    /*!
     * @brief This function returns the value of member color_r
     * @return Value of member color_r
     */
    eProsima_user_DllExport float color_r() const;

    /*!
     * @brief This function returns a reference to member color_r
     * @return Reference to member color_r
     */
    eProsima_user_DllExport float& color_r();

    /*!
     * @brief This function sets a value in member color_g
     * @param _color_g New value for member color_g
     */
    eProsima_user_DllExport void color_g(
            float _color_g);

    /*!
     * @brief This function returns the value of member color_g
     * @return Value of member color_g
     */
    eProsima_user_DllExport float color_g() const;

    /*!
     * @brief This function returns a reference to member color_g
     * @return Reference to member color_g
     */
    eProsima_user_DllExport float& color_g();

    /*!
     * @brief This function sets a value in member color_b
     * @param _color_b New value for member color_b
     */
    eProsima_user_DllExport void color_b(
            float _color_b);

    /*!
     * @brief This function returns the value of member color_b
     * @return Value of member color_b
     */
    eProsima_user_DllExport float color_b() const;

    /*!
     * @brief This function returns a reference to member color_b
     * @return Reference to member color_b
     */
    eProsima_user_DllExport float& color_b();

    /*!
     * @brief This function sets a value in member color_a
     * @param _color_a New value for member color_a
     */
    eProsima_user_DllExport void color_a(
            float _color_a);

    /*!
     * @brief This function returns the value of member color_a
     * @return Value of member color_a
     */
    eProsima_user_DllExport float color_a() const;

    /*!
     * @brief This function returns a reference to member color_a
     * @return Reference to member color_a
     */
    eProsima_user_DllExport float& color_a();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const MarkerMsg& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    uint32_t m_seq;
    uint32_t m_secs;
    uint32_t m_nsecs;
    std::string m_frame_id;
    std::string m_ns;
    int32_t m_id;
    int32_t m_type;
    int32_t m_action;
    float m_position_x;
    float m_position_y;
    float m_position_z;
    float m_orientation_x;
    float m_orientation_y;
    float m_orientation_z;
    float m_orientation_w;
    float m_scale_x;
    float m_scale_y;
    float m_scale_z;
    float m_color_r;
    float m_color_g;
    float m_color_b;
    float m_color_a;
};

#endif // _MARKERMSG_H_