// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TwistMsg.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _TWISTMSG_H_
#define _TWISTMSG_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TwistMsg_SOURCE)
#define TwistMsg_DllAPI __declspec( dllexport )
#else
#define TwistMsg_DllAPI __declspec( dllimport )
#endif // TwistMsg_SOURCE
#else
#define TwistMsg_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TwistMsg_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure TwistMsg defined by the user in the IDL file.
 * @ingroup TWISTMSG
 */
class TwistMsg
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TwistMsg();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TwistMsg();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object TwistMsg that will be copied.
     */
    eProsima_user_DllExport TwistMsg(
            const TwistMsg& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object TwistMsg that will be copied.
     */
    eProsima_user_DllExport TwistMsg(
            TwistMsg&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object TwistMsg that will be copied.
     */
    eProsima_user_DllExport TwistMsg& operator =(
            const TwistMsg& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object TwistMsg that will be copied.
     */
    eProsima_user_DllExport TwistMsg& operator =(
            TwistMsg&& x);

    /*!
     * @brief This function sets a value in member linear_x
     * @param _linear_x New value for member linear_x
     */
    eProsima_user_DllExport void linear_x(
            double _linear_x);

    /*!
     * @brief This function returns the value of member linear_x
     * @return Value of member linear_x
     */
    eProsima_user_DllExport double linear_x() const;

    /*!
     * @brief This function returns a reference to member linear_x
     * @return Reference to member linear_x
     */
    eProsima_user_DllExport double& linear_x();

    /*!
     * @brief This function sets a value in member linear_y
     * @param _linear_y New value for member linear_y
     */
    eProsima_user_DllExport void linear_y(
            double _linear_y);

    /*!
     * @brief This function returns the value of member linear_y
     * @return Value of member linear_y
     */
    eProsima_user_DllExport double linear_y() const;

    /*!
     * @brief This function returns a reference to member linear_y
     * @return Reference to member linear_y
     */
    eProsima_user_DllExport double& linear_y();

    /*!
     * @brief This function sets a value in member linear_z
     * @param _linear_z New value for member linear_z
     */
    eProsima_user_DllExport void linear_z(
            double _linear_z);

    /*!
     * @brief This function returns the value of member linear_z
     * @return Value of member linear_z
     */
    eProsima_user_DllExport double linear_z() const;

    /*!
     * @brief This function returns a reference to member linear_z
     * @return Reference to member linear_z
     */
    eProsima_user_DllExport double& linear_z();

    /*!
     * @brief This function sets a value in member angular_x
     * @param _angular_x New value for member angular_x
     */
    eProsima_user_DllExport void angular_x(
            double _angular_x);

    /*!
     * @brief This function returns the value of member angular_x
     * @return Value of member angular_x
     */
    eProsima_user_DllExport double angular_x() const;

    /*!
     * @brief This function returns a reference to member angular_x
     * @return Reference to member angular_x
     */
    eProsima_user_DllExport double& angular_x();

    /*!
     * @brief This function sets a value in member angular_y
     * @param _angular_y New value for member angular_y
     */
    eProsima_user_DllExport void angular_y(
            double _angular_y);

    /*!
     * @brief This function returns the value of member angular_y
     * @return Value of member angular_y
     */
    eProsima_user_DllExport double angular_y() const;

    /*!
     * @brief This function returns a reference to member angular_y
     * @return Reference to member angular_y
     */
    eProsima_user_DllExport double& angular_y();

    /*!
     * @brief This function sets a value in member angular_z
     * @param _angular_z New value for member angular_z
     */
    eProsima_user_DllExport void angular_z(
            double _angular_z);

    /*!
     * @brief This function returns the value of member angular_z
     * @return Value of member angular_z
     */
    eProsima_user_DllExport double angular_z() const;

    /*!
     * @brief This function returns a reference to member angular_z
     * @return Reference to member angular_z
     */
    eProsima_user_DllExport double& angular_z();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const TwistMsg& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    double m_linear_x;
    double m_linear_y;
    double m_linear_z;
    double m_angular_x;
    double m_angular_y;
    double m_angular_z;
};

#endif // _TWISTMSG_H_